### ISSUE TITLE
Summary of Departments and Layout Report

### ISSUE THREAD

**Issue by HarunCelikOtto** [DSPG-2023/Grocery#10]
Look through the report document for "AGMRC - Departments and Layout.docx" and create a summary of the contents and the important sections. Place the notes into your OneNote notes section.

**Comment by alexcory1** [comment]
In my section of the OneNote

**Comment by HarunCelikOtto** [comment]
Thank you for the notes, great summary.

Is it possible to document ways we can do the following with that information?

- What kind of data will we need?
- Where can we find that kind of data?
- What's the resolution of that data?
- Once we have the data, what will we need to do to make it fit our projects needs?

**Comment by alexcory1** [comment]
Not entirely sure what all we would need for data for this section, as the article was more or less explaining the general design standards of grocery stores. We could potentially look for data about the profitability of different optional departments and make a tool to help figure out if those would be worth investing in, but I don't know if that would really be feasible within the scope of the project.
________________________________
